export const genders = [
    {
      value: 'male',
      label: 'Male',
    },
    {
      value: 'female',
      label: 'Female',
    },
  ];
  
  export const heights = [
    { value: '4.5', label: '4"5 feet' },
    { value: '4.6', label: '4"6 feet' },
    { value: '4.7', label: '4"7 feet' },
    { value: '4.8', label: '4"8 feet' },
    { value: '4.9', label: '4"9 feet' },
    { value: '4.10', label: '4"10 feet' },
    { value: '4.11', label: '4"11 feet' },
    { value: '5', label: '5 feet' },
    { value: '5.1', label: ' 5"1 feet' },
    { value: '5.2', label: '5"2 feet' },
    { value: '5.3', label: '5"3 feet' },
    { value: '5.4', label: '5"4 feet' },
    { value: '5.5', label: '5"5 feet' },
    { value: '5.6', label: '5"6 feet' },
    { value: '5.7', label: '5"7 feet' },
    { value: '5.8', label: '5"8 feet' },
    { value: '5.9', label: '5"9 feet' },
    { value: '5.10', label: '5"10 feet' },
    { value: '5.11', label: '5"11 feet' },
    { value: '6', label: '6 feet' },
    { value: '6.1', label: '6"1 feet' },
    { value: '6.2', label: '6"2 feet' },
    { value: '6.3', label: '6"3 feet' },
    { value: '6.4', label: '6"4 feet' },
    { value: '6.5', label: '6"5 feet' },
    { value: '6.6', label: '6"6 feet' },
  ];
  
  export const maritialStats = [
    { value: 'Unmarried', label: 'Unmarried' },
    { value: 'Widowed', label: 'Widowed' },
    { value: 'Seperated', label: 'Seperated' },
    { value: 'Awaiting Divorce', label: 'Awaiting Divorce' },
    { value: 'Divorced', label: 'Divorced' },
    { value: 'Divorced With Child', label: 'Divorced With Child' },
  ];
  
  export var yesNo = [
    { value: 'yes', label: 'Yes' },
    { value: 'no', label: 'No' },
  ];
  
  export var NoYes = [
    { value: 'no', label: 'No' },
    { value: 'yes', label: 'Yes' },
  ];
  
  export const yesNoDontKnow = [
    { value: 'no', label: 'No' },
    { value: 'yes', label: 'Yes' },
    { value: "I don't know", label: "I don't know" },
  ];
  
  export const devnagriInitials = [
    { value: 'अ', label: 'अ' },
    { value: 'ई', label: 'ई' },
    { value: 'उ', label: 'उ' },
    { value: 'ए', label: 'ए' },
    { value: 'ओ', label: 'ओ' },
    { value: 'का', label: 'का' },
    { value: 'की', label: 'की' },
    { value: 'कु', label: 'कु' },
    { value: 'के', label: 'के' },
    { value: 'को', label: 'को' },
    { value: 'खी', label: 'खी' },
    { value: 'खू', label: 'खू' },
    { value: 'खे', label: 'खे' },
    { value: 'खो', label: 'खो' },
    { value: 'गा', label: 'गा' },
    { value: 'गी', label: 'गी' },
    { value: 'गु', label: 'गु' },
    { value: 'गे', label: 'गे' },
    { value: 'गो', label: 'गो' },
    { value: 'घ', label: 'घ' },
    { value: 'ङ', label: 'ङ' },
    { value: 'च', label: 'च' },
    { value: 'ची', label: 'ची' },
    { value: 'चु', label: 'चु' },
    { value: 'चे', label: 'चे' },
    { value: 'चो', label: 'चो' },
    { value: 'छ', label: 'छ' },
    { value: 'जा', label: 'जा' },
    { value: 'जी', label: 'जी' },
    { value: 'झ', label: 'झ' },
    { value: 'ञ', label: 'ञ' },
    { value: 'टा', label: 'टा' },
    { value: 'टी', label: 'टी' },
    { value: 'टू', label: 'टू' },
    { value: 'टे', label: 'टे' },
    { value: 'टो', label: 'टो' },
    { value: 'ठ', label: 'ठ' },
    { value: 'डा', label: 'डा' },
    { value: 'डी', label: 'डी' },
    { value: 'डू', label: 'डू' },
    { value: 'डे', label: 'डे' },
    { value: 'डो', label: 'डो' },
    { value: 'ढ', label: 'ढ' },
    { value: 'ण', label: 'ण' },
    { value: 'ता', label: 'ता' },
    { value: 'ती', label: 'ती' },
    { value: 'तू', label: 'तू' },
    { value: 'ते', label: 'ते' },
    { value: 'तो', label: 'तो' },
    { value: 'थ', label: 'थ' },
    { value: 'दा', label: 'दा' },
    { value: 'दी', label: 'दी' },
    { value: 'दू', label: 'दू' },
    { value: 'दे', label: 'दे' },
    { value: 'दो', label: 'दो' },
    { value: 'धा', label: 'धा' },
    { value: 'ना', label: 'ना' },
    { value: 'नी', label: 'नी' },
    { value: 'नू', label: 'नू' },
    { value: 'ने', label: 'ने' },
    { value: 'नो', label: 'नो' },
    { value: 'पा', label: 'पा' },
    { value: 'पी', label: 'पी' },
    { value: 'पू', label: 'पू' },
    { value: 'पे', label: 'पे' },
    { value: 'पो', label: 'पो' },
    { value: 'फा', label: 'फा' },
    { value: 'भा', label: 'भा' },
    { value: 'भी', label: 'भी' },
    { value: 'भू', label: 'भू' },
    { value: 'भे', label: 'भे' },
    { value: 'भो', label: 'भो' },
    { value: 'मा', label: 'मा' },
    { value: 'मी', label: 'मी' },
    { value: 'मू', label: 'मू' },
    { value: 'मे', label: 'मे' },
    { value: 'मो', label: 'मो' },
    { value: 'या', label: 'या' },
    { value: 'यी', label: 'यी' },
    { value: 'यू', label: 'यू' },
    { value: 'ये', label: 'ये' },
    { value: 'यो', label: 'यो' },
    { value: 'रा', label: 'रा' },
    { value: 'री', label: 'री' },
    { value: 'रू', label: 'रू' },
    { value: 'रे', label: 'रे' },
    { value: 'रो', label: 'रो' },
    { value: 'ला', label: 'ला' },
    { value: 'ली', label: 'ली' },
    { value: 'लू', label: 'लू' },
    { value: 'ले', label: 'ले' },
    { value: 'लो', label: 'लो' },
    { value: 'वा', label: 'वा' },
    { value: 'वी', label: 'वी' },
    { value: 'वु', label: 'वु' },
    { value: 'वे', label: 'वे' },
    { value: 'वो', label: 'वो' },
    { value: 'ष', label: 'ष' },
    { value: 'सा', label: 'सा' },
    { value: 'सी', label: 'सी' },
    { value: 'सू', label: 'सू' },
    { value: 'से', label: 'से' },
    { value: 'सो', label: 'सो' },
    { value: 'हा', label: 'हा' },
    { value: 'ही', label: 'ही' },
    { value: 'हु', label: 'हु' },
    { value: 'हे', label: 'हे' },
    { value: 'हो', label: 'हो' },
  ];
  
  export const rashis = [
    { value: 'मेष', label: 'मेष' },
    { value: 'वृषभ', label: 'वृषभ' },
    { value: 'मिथुन', label: 'मिथुन' },
    { value: 'कर्क', label: 'कर्क' },
    { value: 'सिंह', label: 'सिंह' },
    { value: 'कन्या', label: 'कन्या' },
    { value: 'तुला', label: 'तुला' },
    { value: 'वृश्चिक', label: 'वृश्चिक' },
    { value: 'धनु', label: 'धनु' },
    { value: 'मकर', label: 'मकर' },
    { value: 'कुम्भ', label: 'कुम्भ' },
    { value: 'मीन', label: 'मीन' },
  ];
  
  export const educationList = [
    { value: 'Undergraduate', label: 'Undergraduate' },
    { value: 'Graduate', label: 'Graduate' },
    { value: 'Post Graduate', label: 'Post Graduate' },
    { value: 'Masters', label: 'Masters' },
    { value: 'Doctorate', label: 'Doctorate' },
  ];
  
  export const subscriptionFeatures = [
    'Direct message to all profiles',
    'Unlimited profile visits',
    'All the features of the app',
    'Access for one year',
  ];
  
  
  